### ISSUE TITLE
On version management

### ISSUE THREAD

**Issue by Ly4m** [Ly4m/core-abstract-sample#2]
When working with so many modules, versioning seems to be quite cumbersome, is there any tool I can use to help with that or should I keep manually updating each version ?

**Comment by lusoalex** [comment]
Hello, 
There's no real tooling. (At least I am not using any...)
The "main" repo keep reference to submodules:

```bash
cd submodule_directory
git checkout v1.0
cd ..
git add submodule_directory
git commit -m "moved submodule to v1.0"
git push
```

Is it ok for you?

**Comment by Ly4m** [comment]
I see, thank you !

Should I use submodules aswell for my test ?
